#!/usr/bin/env python

import csv
from datetime import datetime
from io import StringIO
import json
import logging
import sys

import click
import requests


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


with open(".ghcreds") as f:
    USERNAME, APIKEY = [x.strip() for x in f.readlines()]


@click.group()
def cli():
    pass


def get_issue_from_file(filename):
    with open(filename) as f:
        issues = json.load(f)


def write_issues_csv(issue_list, filename):
    s = StringIO()
    sw = csv.writer(s)

    for issue in sorted(issues, key=lambda x:int(x['number'])):
        i = Issue(issue)
        sw.writerow([i.number, i.title, i.milestone, i.priority, i.actions_str])

    with open(filename, "wt") as f2:
        f2.write(s.getvalue())


def get_links(r):
    links = {}

    if 'link' in r.headers:
        for link in r.headers['link'].split(','):
            url, rel = link.split(';')
            url = url.strip().strip('<>')
            rel = rel.split('"')[1]
            links[rel] = url

    return links


def call_api(url):
    authorization = 'token {}'.format(APIKEY)
    user_agent = USERNAME + " python-requests/" + requests.__version__
    headers = {'Authorization': authorization, 'User-Agent': user_agent}

    response = requests.get(url, headers=headers)

    if response.status_code != requests.codes.ok:
        raise ValueError(f"API Error ({url}): {response.json()['message']}")

    return response


def _unpaginate(url):
    """Repeatedly call an API until there is no 'next' parameter.

    The URL should should return JSON consisting of a list of items.
    """
    while url:
        # Rudimentary logging while an operation is in progress
        print(url, file=sys.stderr)
        r = call_api(url)
        url = get_links(r).get('next')

        for item in r.json():
            yield item


def get_issues(repo):
    issues = []

    url = "https://api.github.com/repos/%s/issues" % repo
    issues = _unpaginate(url)

    return issues


def get_closed_issues(repo):
    issues = []

    url = "https://api.github.com/repos/%s/issues?state=closed" % repo
    issues = _unpaginate(url)

    return issues


# The closed date is an ISO-formatted string in UTC, so we can just use string
# comparison to find issues closed between 2019-05-01 and 2020-05-01.
START_DATE = "2019-05-01"
END_DATE = "2020-05-01"

def print_issues(issues, sort=False):
    if sort:
        issues = sorted(issues, key=lambda x:int(x['number']))

    # Header Row
    print("\t".join(['URL', 'Title', "State", "Created At", "Closed At", "Labels"]))
    for issue in issues:
        i = Issue(issue)
        if i.closed_at <= START_DATE or i.closed_at >= END_DATE:
            continue
        fields =  [i.url, i.title, i.state, i.created_at, i.closed_at, ",".join(i.labels)]
        print("\t".join(str(x) for x in fields))


def ratelimit_info(response):
    print(response.headers["X-RateLimit-Limit"])
    print(response.headers["X-RateLimit-Remaining"])
    reset_date = float(response.headers["X-RateLimit-Reset"])
    print(datetime.fromtimestamp(reset_date).isoformat())


class Issue(object):

    def __init__(self, d):
        self._d = d

    @property
    def number(self):
        return self._d['number']

    @property
    def title(self):
        return self._d['title']

    @property
    def url(self):
        return self._d['html_url']

    @property
    def milestone(self):
        if not self._d['milestone']:
            return None
        return self._d['milestone']['title']

    @property
    def labels(self):
        return [lbl['name'] for lbl in self._d['labels']]

    @property
    def priority(self):
        for l in self.labels:
            if l.startswith("Pri"):
                return l
        return None

    @property
    def actions(self):
        return [str(l) for l in self.labels if l in
                ('New Type', 'Expand Type', 'Modify Type', 'Documentation')]

    @property
    def actions_str(self):
        return ", ".join(i.actions) if i.actions else ""

    @property
    def state(self):
        return self._d['state']

    @property
    def created_at(self):
        return self._d['created_at']

    @property
    def closed_at(self):
        return self._d['closed_at']

    def as_dict(self):
        pprint(self._)


@cli.command()
@click.argument("org")
def tfa(org):
    url = "https://api.github.com/orgs/%s/members?filter=2fa_disabled" % org

    for user in _unpaginate(url):
        print(user['login'])


@cli.command()
@click.argument('repo')
def issues(repo):
    print_issues(get_closed_issues(repo), sort=True)


@cli.command()
@click.argument('org')
def repos(org):
    url = "https://api.github.com/orgs/%s/repos" % org

    for repo in sorted(_unpaginate(url), key=lambda x: x['updated_at']):
        print(repo['updated_at'], repo['name'])


if __name__ == "__main__":
    cli()
